### ISSUE TITLE
empty bigwig files

### ISSUE THREAD

**Issue by mortunco** [inutano/chip-atlas#14]
Hi,

I see that some of my GSM files have empty bigwig files. I just wanted to ask if there is a spesific region. (otherwise I will download raw fastqs and run through the same pipeline on my end).

THANK YOU VERY MUCH FOR THIS CRAZY VALUABLE DATABASE. Like If you guys hadnt processed this data, it would have gotten me analyse 150 chipseq files. I appreciate your work and effort!

```
how i install
cat interested_gsm-srx.txt  | parallel --verbose --col-sep "\t" -j10  "wget --no-check-certificate -O {1}.bigWig  http://dbarchive.biosciencedbc.jp/kyushu-u/hg19/eachData/bw/{2}.bw"
```
empty bigwigs
```
(base) [tmorova@linuxsrv006 raw-data]$ cat problematic
GSM3290778      SRX4404396
GSM3290777      SRX4404395
GSM3290774      SRX4404392
GSM3290773      SRX4404391
GSM696844       SRX019092
GSM696843       SRX019091
GSM503907       SRX017347
GSM503906       SRX017346
```

**Comment by shinyaoki** [comment]
Hi,

Thank you for using ChIP-Atlas.
I found that GSMs of your interest are not archived in ChIP-Atlas due to following reasons:
GSM329077*: The data were submitted on Aug 2019, so they will be available from next update of ChIP-Atlas.
GSM50390*: The "Library Strategy" is "MNase-Seq".
GSM69684*: The "Library Strategy" is "OTHER".
(The "Library Strategy" to be archived in ChIP-Atlas are "ChIP-seq" or "DNase-Hypersensitivity".)

I would appreciate your understanding for our update interval and collecting policy of ChIP-Atlas data.

Cheers,
Shinya

**Comment by mortunco** [comment]
oh thank you very much for the explanation.

Best regards,

T.
