### ISSUE TITLE
Downloading Data as Separate Bed Files

### ISSUE THREAD

**Issue by rantingswede373** [inutano/chip-atlas#2]
Hey Guys,

Neat tool, I really like the web interface and the clear explanation of the pipeline steps. 

I was wondering if it's possible to download all datasets for a category as separate bed files in a compressed folder. For instance, I want to download all TF ChIP peak regions from mouse liver. When using the data browser the default is to combine all peaks into a single bed file which seems...odd. I can probably figure out how to split the file based on track information in column 4, but this seems more complicated than it needs to be.

Let me know if I'm missing some feature.

Thanks,

Bryan

**Comment by inutano** [comment]
Hi Bryan,

For that purpose, you can download bed files directly from our server by using the file list. See "Assembled Peak-call data used in Peak Browser" in the "Download" section of the wiki.
https://github.com/inutano/chip-atlas/wiki#downloads_doc

First, you need to download [file list](http://dbarchive.biosciencedbc.jp/kyushu-u/metadata/fileList.tab), then you can create the list of URL to download assembled bed files for mouse liver by doing like;

```
cat fileList.tab| awk -F '\t' '$2 == "mm9" && $5 == "Liver" { print "http://dbarchive.biosciencedbc.jp/kyushu-u/mm9/assembled/" $1 ".bed" }'
```

Scheme of the fileList.tab is [here](https://github.com/inutano/chip-atlas/wiki#fileList_schema).

We're afraid that we don't offer compressed file download option, since we have limited disk space, but hope this will work for you.

**Comment by rantingswede373** [comment]
Sorry it took me a while to get back to you, but this works really well and is a great option for people with similar goals. Thanks again for responding so quickly and helpfully!
