### ISSUE TITLE
メンテナンス後のsubmitエラーについて

### ISSUE THREAD

**Issue by qqsearch** [inutano/chip-atlas#22]
いつも利用させていただいています。

Enrichment Analysisでbed fileをsubmitしたところ下記のエラーがでました。

Something went wrong: Please let us know to fix the problem, click 'contact us' below this page.{"readyState":4,"responseText":"<h1>Internal Server Error</h1>","status":500,"statusText":"error"}

対応していただけますでしょうか。よろしくお願いいたします。

**Comment by inutano** [comment]
@qqsearch ご報告どうもありがとうございます。こちら Enrichment Analysis が依存している遺伝研スパコンの機器故障が原因と判明しており、そちらが修正されるまで約一日ほどかかる見込みです。それまでの間一時的に停止しています。ご迷惑おかけしますが、よろしくおねがいします。

//

For others who got the same error:
An internal server error on Enrichment Analysis (users may encounter on 2 Dec 2020) was due to the backend system failure which is being fixed. It may take a day to recover, we stop the feature until the system is back.

**Comment by inutano** [comment]
@qqsearch ただいま遺伝研スパコンの方で別機器によって起動してもらいましたので、利用可能になっています。お試しください！

**Comment by qqsearch** [comment]
動作を確認しました。
ありがとうございます！
