### ISSUE TITLE
Updating old analysis - peak numbers per experiment very different?

### ISSUE THREAD

**Issue by michael-imbeault** [inutano/chip-atlas#60]
Updating an enrichment analysis prior to submission for publication, and I was very surprised that most results are very different.

Tracking it down, there is something odd when I compare the old saved results to the new ones - for any experiment in the chip-atlas dataset, the peak number is much lower - therefore, the overlap with my dataset is also much lower.

For example:

Old dataset:
SRX1161166	TFs and others	NR3C1	Breast	MCF-7	13463	21/758	2/758	-4.23037	-2.43098	10.5

New dataset:
SRX1161166	TFs and others	NR3C1	Breast	MCF-7	1848	0/758	0/758	0	0	inf

13463 peaks for the old dataset for this experiment vs 1848 in the new one - its a massive difference, and the overlaps are also wildly different (21 vs 0, all experiments).

All files follow the same trend with much fewer peaks than before - however, the files in the 'download' section of the website still correspond to the old dataset peak number. 

Let me know if you have a simple explanation. Same parameters with threshold at 50.

hg19 for everything, haven't checked if it affects hg38 as well

**Comment by inutano** [comment]
Hi @michael-imbeault , I am very sorry for having not responded, and for your inconvenience on an important phase of your work.

At the time when you raised this issue, we have made some important changes on the ChIP-Atlas application backend (We probably missed your issue because of this). I suspect possibly you encountered a bug while we updated the running application. From your result, the decreased number of the peaks may come from the app that handled your threshold setting wrong (perhaps app did the analysis with 500 despite you set it to 50).

We just tested your case with the current running application, and found the issue may already have resolved.

```
hg19, threshold 50, Try with example
SRX1161166	TFs and others	NR3C1	Breast	MCF-7	13463	133/1000	3/1000	-37.0	-36.0	44.33	TRUE
```

Please accept our apologies, and feel free to let us know if you still have a problem.
